#!/usr/bin/env php
<?php

use Gnugat\SoulMeMaybe\Application;
use Gnugat\SoulMeMaybe\VersionExtractor;

require __DIR__.'/../vendor/autoload.php';

$versionExtractor = new VersionExtractor(__DIR__.'/../VERSION.md');

/**
 * Main file instanciating the Application.
 *
 * @author Loic Chardonnet <loic.chardonnet@gmail.com>
 */
$application = new Application($versionExtractor);

$application->run();
